Document: cpupower
Title: Debian cpupower Manual
Author: <insert document author here>
Abstract: This manual describes what cpupower is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cpupower/cpupower.sgml.gz

Format: postscript
Files: /usr/share/doc/cpupower/cpupower.ps.gz

Format: text
Files: /usr/share/doc/cpupower/cpupower.text.gz

Format: HTML
Index: /usr/share/doc/cpupower/html/index.html
Files: /usr/share/doc/cpupower/html/*.html
